version: "3.9"

services:
  mongodb:
    image: mongo:7
    container_name: lychat_mongodb
    restart: unless-stopped
    ports:
      - "27016:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: Lycody
      MONGO_INITDB_ROOT_PASSWORD: Admin@123
    volumes:
      - mongo_data:/data/db
    networks:
      - lychat_network

  server:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    container_name: lychat_server
    restart: unless-stopped
    ports:
      - "3004:3004"
    env_file:
      - .env
    environment:
      MONGO_URI: mongodb://Lycody:Admin%40123@mongodb:27017/lychat?authSource=admin
      CLIENT_URL: http://localhost:3002
    depends_on:
      - mongodb
    networks:
      - lychat_network

volumes:
  mongo_data:

networks:
  lychat_network:
    driver: bridge