apiVersion: apps/v1
kind: Deployment
metadata:
  name: lychat-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lychat-backend
  template:
    metadata:
      labels:
        app: lychat-backend
    spec:
      containers:
        - name: lychat-backend
          image: lycody/lychat_server_side:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5050
          env:
            - name: MONGO_URI
              value: "mongodb://mongodb:27017/lychat"