name: lychat-api

services:
  api:
    type: application

    build:
      context: .
      dockerfile: ./Dockerfile

    port: 5008

    replicas: 1

    expose: true

    health:
      path: /api/health
      initialDelaySeconds: 15
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 6

    env:
      NODE_ENV: production
      PORT: "5008"

      MONGO_URI: "${mongo.url}"

      REDIS_URL: "${redis.url}"

  mongo:
    type: database

    engine: mongodb

    port: 27017

    storage: 10Gi

  redis:
    type: cache

    engine: redis

    port: 6379
