name: lychat-api

services:
  backend:
    type: application

    build:
      context: .
      dockerfile: ./Dockerfile

    port: 5008

    expose: true

    health:
      path: /api/health

    env:
      NODE_ENV: production
      PORT: "5008"