apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: shared-date-logs
        emptyDir: {}
      containers:
      - name: container-writing-dates
        image: alpine
        command: ["/bin/sh"]
        args: ["-c", "while true; do date >> /var/log/index.html; sleep 10;done"]
        volumeMounts:
        - name: shared-date-logs
          mountPath: /var/log
      - name: container-serving-dates
        image: nginx:1.20.0
        ports:
        - containerPort: 80
        volumeMounts:
        - name: shared-date-logs
          mountPath: /usr/share/nginx/html